version: 2.1
jobs:
  build:
    shell: /bin/bash --login
    docker:
      - image: circleci/ruby:2.5
      - image: circleci/postgres:11-alpine
    environment:
      RAILS_ENV: test
      RACK_ENV: test
      DATABASE_URL: postgres://postgres:@localhost:5432/credit_request_test
    steps:
      - checkout
      - run: echo -e "export RAILS_ENV=test\nexport RACK_ENV=test" >> $BASH_ENV
      - run:
          name: 'Install bundler'
          command: |
            gem update --system
            gem install bundler
      - run: bundle install
      - run: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Running rubocop
          command: bundle exec rubocop
      - run:
          name: Running rspecs
          command:
              bundle exec rspec --format progress
  production:
    docker:
      - image: buildpack-deps:trusty
    environment:
      HEROKU_APP_NAME: credit-request-api
    steps:
      - checkout
      - run:
          name: Installing Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
      - run:
          name: Deploy Master to credit-request-api
          command: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $CIRCLE_BRANCH
      - run: heroku restart --app $HEROKU_APP_NAME

workflows:
  version: 2
  deployment:
    jobs:
      - build
      - production:
          requires:
            - build
          filters:
            branches:
              only: master
